services:
  - type: web
    name: netflix-recommend
    env: node
    buildCommand: npm install && npx prisma migrate deploy
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: netflix-recommend-db
          property: connectionString
databases:
  - name: netflix-recommend-db
    plan: free
